### ISSUE TITLE
NEI Time crash

### ISSUE THREAD

**Issue by CorneliusCornbread** [23Link89/Link-s-madpack#1]
You can crash your game while on a space station by disabling night or day

Console output:
[14:29:31] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel NEI
java.lang.RuntimeException: java.io.FileNotFoundException: E:\Minecraft Data\MC Curse\Instances\Link's madpack\saves\Space Station\DIM_SPACESTATION2\NEI\world.dat (The system cannot find the path specified)
    at codechicken.nei.NEIServerConfig.saveWorld(NEIServerConfig.java:106) ~[NEIServerConfig.class:?]
    at codechicken.nei.NEIServerConfig.disableAction(NEIServerConfig.java:137) ~[NEIServerConfig.class:?]
    at codechicken.nei.NEISPH.handlePropertyChange(NEISPH.java:110) ~[NEISPH.class:?]
    at codechicken.nei.NEISPH.handlePacket(NEISPH.java:60) ~[NEISPH.class:?]
    at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:117) ~[PacketCustom$ServerInboundHandler.class:?]
    at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) ~[PacketCustom$CustomInboundHandler.class:?]
    at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) ~[PacketCustom$CustomInboundHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.io.FileNotFoundException: E:\Minecraft Data\MC Curse\Instances\Link's madpack\saves\Space Station\DIM_SPACESTATION2\NEI\world.dat (The system cannot find the path specified)
    at java.io.FileOutputStream.open(Native Method) ~[?:1.8.0_25]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_25]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_25]
    at codechicken.nei.NEIServerUtils.writeNBT(NEIServerUtils.java:399) ~[NEIServerUtils.class:?]
    at codechicken.nei.NEIServerConfig.saveWorld(NEIServerConfig.java:104) ~[NEIServerConfig.class:?]
    ... 19 more

**Comment by CorneliusCornbread** [comment]
Patched in TrashCraft 2.0
